### ISSUE TITLE
Icons do not load in RN 0.27+

### ISSUE THREAD

**Issue by zevmo** [bradbumbalough/react-initicons#1]
It seems that the icons aren't rendering using React Native 0.27+

**Comment by bradbyte** [comment]
@zevmo it probably has something to do with Component being required from `react` and not `react-native`. We're not using `0.27` in our production app, so if you want to submit a PR for this implementation we'll review it! Thanks for checking out the project!

**Comment by bradbyte** [comment]
@zevmo Fixed in `0.2.0`.
